In [1]:
# Write a function so that the columns of the output matrix are powers of the input vector.
# The order of the powers is determined by the increasing boolean argument. Specifically, when
# increasing is False, the i-th output column is the input vector raised element-wise to the power
# of N - i - 1.
# HINT: Such a matrix with a geometric progression in each row is named for AlexandreTheophile Vandermonde.

import numpy as np


def myVander(input_vector, n, increasing=False):
    
    if increasing:
        return [[i**(j) for j in range(n)] for i in input_vector]
    return [[i**(n-j-1) for j in range(n)] for i in input_vector]

def display_vander(m):
    for i in m:
        print(i)
    
input_vector = [1,2,3,4,5]
n=4

print("Using Built in Function Increasing True \n")
print(np.vander(input_vector, N=n, increasing=True))

print("\nUsing Manual Function Increasing True \n")
m = myVander(input_vector, n, True)
display_vander(m)

print('*'*100)
print("\nUsing Built in Function Increasing False \n")
print(np.vander(input_vector, N=n, increasing=False))

print("\nUsing Manual Function Increasing False \n")
m = myVander(input_vector, n, False)
display_vander(m)

Using Built in Function Increasing True 

[[  1   1   1   1]
 [  1   2   4   8]
 [  1   3   9  27]
 [  1   4  16  64]
 [  1   5  25 125]]

Using Manual Function Increasing True 

[1, 1, 1, 1]
[1, 2, 4, 8]
[1, 3, 9, 27]
[1, 4, 16, 64]
[1, 5, 25, 125]
****************************************************************************************************

Using Built in Function Increasing False 

[[  1   1   1   1]
 [  8   4   2   1]
 [ 27   9   3   1]
 [ 64  16   4   1]
 [125  25   5   1]]

Using Manual Function Increasing False 

[1, 1, 1, 1]
[8, 4, 2, 1]
[27, 9, 3, 1]
[64, 16, 4, 1]
[125, 25, 5, 1]


In [2]:
# Problem Statement 2: 
 
# Given a sequence of n values x1, x2, ..., xn and a window size k>0, the k-th moving average of the given 
# sequence is defined as follows: 
 
# The moving average sequence has n-k+1 elements as shown below. 
 
# The moving averages with k=4 of a ten-value sequence (n=10) is shown below 
 
# i 1  2  3  4  5  6  7  8  9 10  
# ===== == == == == == == == == == ==  
# Input 10 20 30 40 50 60 70 80 90 100  
# y1      25 = (10+20+30+40)/4  
# y2      35 = (20+30+40+50)/4  
# y3      45 = (30+40+50+60)/4  
# y4      55 = (40+50+60+70)/4 
# y5      65 = (50+60+70+80)/4 
# y6      75 = (60+70+80+90)/4 
# y7      85 = (70+80+90+100)/4 
 
 
# Thus, the moving average sequence has n-k+1=10-4+1=7 values. 
# Question: Write a function to find moving average in an array over a window:         
# Test it over [3, 5, 7, 2, 8, 10, 11, 65, 72, 81, 99, 100, 150] and window of 3. 

def my_mov_average(array, window):
    
    n = array.shape[0]
    mov_average = [ sum([(array[i+j]) for j in range(window)])/window for i in range(n-window+1)]
    return mov_average

A = np.arange(10, 110, 10)
window = 4
print("Moving average for example function")
print(my_mov_average(A, window))
print('\n')

B = np.array([3, 5, 7, 2, 8, 10, 11, 65, 72, 81, 99, 100, 150])
window = 3
print("Moving average for test fucnction")
print(my_mov_average(B, window))

Moving average for example function
[25.0, 35.0, 45.0, 55.0, 65.0, 75.0, 85.0]


Moving average for test fucnction
[5.0, 4.666666666666667, 5.666666666666667, 6.666666666666667, 9.666666666666666, 28.666666666666668, 49.333333333333336, 72.66666666666667, 84.0, 93.33333333333333, 116.33333333333333]
